### ISSUE TITLE
Archived sprints should not be considered for Planning

### ISSUE THREAD

**Issue by hermannoffen** [TWENTY-20/youtrack-multi-sprint-planner#1]
In version 1.0.0, the list of sprints contains archived sprints.

Personally, I think they should just be filtered out, as those should not be considered for planning.

**Comment by sporth-tw20** [comment]
Thanks for the suggestion. We're planning to address this in a release next week.

**Comment by sporth-tw20** [comment]
The release is now available and should fix this issue
