### ISSUE TITLE
Sorting not working in sprints

### ISSUE THREAD

**Issue by dxtr0dsgnz** [TWENTY-20/youtrack-multi-sprint-planner#2]
Youtrack 2024.3.44799 / Multi Sprint Planner 1.1.0

1. Drag ISSUE-1 and ISSUE-2 from backlog to a sprint
2. Change order of ISSUE-1 and ISSUE-2 via drag and drop in sprint
3. While the new sorting will visually be applied, it is not saved and it's lost when you reload the page.

Best regards,
Julian

**Comment by stephanweck** [comment]
Hi Julian,
we check if there is an option to save the sort state in our App.
In general we are interested why this feature is important for you. Our App helps to manage multiple sprints and prepare them fast and easy for the actual development process. From our understanding the sorting of the tickets happens later in the Agile board when the Sprint is running. There it depends on different things like swimlanes, status etc.
But maybe you can give us more insights.

best regards

Stephan from twenty20

**Comment by dxtr0dsgnz** [comment]
Hi Stephan,
thanks for your reply.
I agree that your app helps to manage multiple sprints in a great way. This view is one of the most missed ones since we migrated from Jira Server to Youtrack. Thanks for providing this app!

When preparing future sprints, sorting issues in this view is the only way to visualize the priorization those issues have within the sprint. I know that every software company works their own way: while for some the order of the issues within a future sprint may not be important, as their sprint target is to complete all contained issues, for us the order _is_ important, as we are working with customer context and dependencies between issues inside a sprint, which requires some issues to be completed before others. You can't visualize this with swimlanes, status or prio field, as these entities are rather grouping sets of issues than sorting all issues of a certain sprint.
Moreover, we do have multiple teams, while each have their own boards. Sometimes, two teams are working on a single project in different technical areas, so they have their own issues, which need to be planned in a certain timeframe. This requires both teams to place these issues on a certain position in their future sprint.

From a technical view, multi-sprint-planner allows all lists, backlog and sprints, to be sorted via drag and drop. While sorting will be saved in backlog list, it won't be saved in the sprint lists. I think, that's confusing for the users, especially those with a less technical background, and those who know this view from Jira. The latter is not a real argument, but Jira saves the sorting in future sprints, and I think this is a nice and consistent behaviour.

Thanks & best regards,
Julian

**Comment by stephanweck** [comment]
OK - thx for the very deep explanation. I understand your points and we try to solve this issue for you. We are currently working on making the backlog view customizable and after that we try to fix your issue.

**Comment by stephanweck** [comment]
The new version 1.2.0 is now available in the Marketplace for download. We were able to implement your request - you should now be able to sort the issues in the Sprint view. Please feel free to reach out to us if you have further requests.

**Comment by dxtr0dsgnz** [comment]
Hi Stephan,
thanks so much - works great!

Thanks & best regards,
Julian
